# -*- coding: utf-8 -*-
"""financialDataSet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e7JJ8Awj36KmsM0QYTBMcdhft_XMJzBM
"""

# Import Libraries we use for analysis
import pandas as pd
#add a document
myDataSet = pd.read_csv('https://bit.ly/FinancialDataset')

#view observations
myDataSet.head()

#check more info
myDataSet.tail(10)

myDataSet.info()
#information on datamy

myDataSet.describe()
#summary of statistics

myDataSet.shape

myDataSet.columns

myDataSet.year.unique()

myDataSet.marital_status.unique()

myDataSet["Cell Phone Access"].unique()

myDataSet["Type of Job"].unique()

myDataSet.gender_of_respondent.unique()

myDataSet.columns

#viewing unique values
myDataSet.uniqueid.unique()

myDataSet.dtypes

myDataSet["Level of Educuation"].unique()

#import libraries for graphs
import matplotlib.pyplot as plt
import seaborn as sns

myDataSet.dropna(inplace = True)

#plotting a histogram using matplotlib and seaborn
#create a figure and give dimensions
plt.figure(figsize = (8, 5))
sns.distplot(myDataSet['Respondent Age'], color='green')
#title to the graph
plt.title('Distribution for Respondent Age')
plt.xlabel('Respondent')
plt.ylabel('Frequency')
plt.show()

myDataSet['Respondent Age'].mean()

#another one lol
#create afigure and give dimensions
plt.figure(figsize = (12, 8))
sns.countplot(myDataSet['country'])
plt.title('Country Chart', color = 'green', )
plt.xlabel('Country')
plt.ylabel('Frequency')
plt.show()



#another one
plt.figure(figsize = (12, 8))
sns.countplot(myDataSet['marital_status'])

